# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ICEDCamelPlot
                                 A QGIS plugin
 This plugin creates camelplots for each site based on multiple exposure ages and links the camelplots to each site
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-08-05
        copyright            : (C) 2023 by Yingkui Li
        email                : yli32@utk.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Yingkui Li'
__date__ = '2023-08-05'
__copyright__ = '(C) 2023 by Yingkui Li'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ICEDCamelPlot class from file ICEDCamelPlot.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ICED_Camelplots import ICEDCamelPlotPlugin
    return ICEDCamelPlotPlugin(iface)
