# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ICEDCamelPlot
                                 A QGIS plugin
 This plugin creates camelplots for each site based on multiple exposure ages and links the camelplots to each site
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-08-05
        copyright            : (C) 2023 by Yingkui Li
        email                : yli32@utk.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yingkui Li'
__date__ = '2023-08-05'
__copyright__ = '(C) 2023 by Yingkui Li'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon

import processing

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .ICED_Camelplots_provider import ICEDCamelPlotProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class ICEDCamelPlotPlugin(object):

    def __init__(self, iface):
        self.provider = None
        self.iface = iface
        
    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = ICEDCamelPlotProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        icon = os.path.join(os.path.join(cmd_folder, 'camellogo.png'))
        self.action = QAction(
            QIcon(icon),
            u"Camel Plots", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addPluginToMenu(u"&ICE-D Analysis Tools", self.action)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
        self.iface.removePluginMenu(u"&ICE-D Analysis Tools", self.action)
        self.iface.removeToolBarIcon(self.action)        

    def run(self):
        processing.execAlgorithmDialog("ICE-D Analysis Tools:Camel Plots")